# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lli0pZmhRedz2hM7fNcWFtFPlYSy3xE4
"""

import numpy as np
import matplotlib.pyplot as plt

# Yurak urishi chizmasini modellashtirish uchun sun'iy signal yaratamiz
def generate_ecg_waveform(samples=500):
    t = np.linspace(0, 1, samples)  # 2 soniyalik signal uchun vaqt
    ecg = (
        1 * np.sin(2 * np.pi * 1 * t) +
        0.5 * np.sin(2 * np.pi * 3 * t) +
        0.2 * np.sin(2 * np.pi * 50 * t)
    )
    # Yurak urishi impulsini qo'shamiz
    ecg += np.exp(-100 * (t % 0.5)**2) * 5
    return t, ecg

# Signalni yaratamiz
time, ecg_waveform = generate_ecg_waveform()

# Grafikka chizish
plt.figure(figsize=(10, 5))
plt.plot(time, ecg_waveform, label="Yurak urishi chizmasi", color="green")
plt.title("Yurak urishi signali (EKG)")
plt.xlabel("Vaqt (soniya)")
plt.ylabel("Amplitude")
plt.grid(True)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,5,13,24,38])
y=np.array([1,5,13,24,38])
mycolor=['black','yellow','red','brown','green']
size=[10,150,330,630,1360]
plt.scatter(x,y,color=mycolor,s=size)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,5,9,13,13])
mylabels=['cherry','apple','melon','grapes','pear','pumpkin']
myexplode=[0.2,0,0,0,0,0]
plt.pie(x,labels=mylabels,
startangle=90,explode=myexplode)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,5,9,13,13])
mylabels=['cherry','apple','melon','grapes','pear','pumpkin']
plt.pie(x,labels=mylabels)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,25,5,9,13,13])
mylabels=['cherry','apple','melon','grapes','pear','pumpkin']
plt.pie(x,labels=mylabels)
plt.legend(title='Four Fruit:')

plt.show()